## roles/ntp/tasks/main.yml
## Role main file
# vim:ft=ansible:
---
## Initialise distribution-specific variables
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: "Ensure NTP-related packages are installed"
  package: 
    name: ntp 
    state: present

- name: "Ensure tzdata package is installed"
  package:
    name: tzdata
    state: present
  when: ansible_system == "Linux"

- name: Set timezone
  timezone:
    name: '{{ ntp_timezone }}'

- name: "Configure NTP"
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - restart ntp

- name: "Start and Enable ntpd.service"
  service: 
    name: '{{ servicename }}' 
    state: started
    enabled: yes
...
