## roles/ntp/tasks/main.yml
## Role main file
# vim:ft=yaml.ansible:
---
## Initialise distribution-specific variables
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: "Remove Chrony where ntp package is available"
  when: ( 'ntp' in ntp_package ) 
  package:
    name: chrony
    state: absent

- name: "Ensure NTP-related packages are installed"
  package:
    name: '{{ ntp_package }}'
    state: present

- name: "Ensure tzdata package is installed"
  package:
    name: tzdata
    state: present
  when: ansible_system == "Linux"

- name: Set timezone
  timezone:
    name: '{{ ntp_timezone }}'

- name: "Configure NTP"
  when: ( 'ntp' in ntp_package ) 
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - restart ntp

- name: "Configure Chrony"
  when: ( 'chrony' in ntp_package ) 
  template:
    src: chrony.conf.j2
    dest: '{{ ntp_chrony_conf_path }}/chrony.conf'
  notify:
    - restart ntp

- name: "Open firewall if server"
  firewalld:
    service: ntp
    permanent: yes
    state: enabled
    immediate: yes
  when: is_ntp_server
#- name: "Start and Enable ntpd.service"
#  service:
  #    name: '{{ servicename }}'
  #  state: started
  #  enabled: yes
...
